apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation_ecr_rep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geolocation_ecr_rep
  template:
    metadata:
      labels:
        app: geolocation_ecr_rep
    spec:
      containers:
      - name: geolocation_ecr_rep
        image: 823008317281.dkr.ecr.us-west-2.amazonaws.com/geolocation_ecr_rep:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: geolocation_ecr_rep
    k8s-app: geolocation_ecr_rep
  name: geolocation_ecr_rep
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8082
  type: LoadBalancer
  selector:
    app: geolocation_ecr_rep