apiVersion: apps/v1
kind: Deployment
metadata:
   name: geolocation-ecr-rep-deployment
spec:
  replicas: 3
  selector:
     matchLabels:
        app: geolocation-ecr-rep-app
  template: 
      metadata: 
         labels: 
           app: geolocation-ecr-rep-app
      spec: 
        containers:
        - name: geolocation-ecr-rep-app
          image: 823008317281.dkr.ecr.us-west-2.amazonaws.com/geolocation_ecr_rep:latest
          imagePullPolicy: Always
          ports:
           - containerport: 8082
  # Service type loadbalancer
  ---:
  apiVersion: v1
  kind: Service
  metadata:
    labels:
       app: geolocation-ecr-rep-app
       k8s-app: geolocation-ecr-rep-app
    name: geolocation-ecr-rep-app
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8082
    type: loadbalancer
    selector:
       app: geolocation-ecr-rep-app