apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation-ecr-rep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geolocation-ecr-rep
  minReadySeconds: 10
  strategy: 
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: geolocation_ecr_rep
    spec:
      containers:
      - name: geolocation_ecr_rep
        image: 823008317281.dkr.ecr.us-west-2.amazonaws.com/geolocation_ecr_rep:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082

--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: geolocation-ecr-rep
    k8s-app: geolocation-ecr-rep
  name: geolocation-ecr-rep
spec:
  selector:
    app: geolocation-ecr-rep
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8082
  type: LoadBalancer
