apiVersion: apps/v1
kind: Deployment
metadata:
  name: Geolocation-ecr-rep-deployement
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Geolocation-ecr-rep-deployement
  minReadySeconds: 10
  strategy: 
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: Geolocation-ecr-rep-app
    spec:
      containers:
      - name: Geolocation-ecr-rep-app
        image: 823008317281.dkr.ecr.us-west-2.amazonaws.com/geolocation_ecr_rep:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082

--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: Geolocation-ecr-rep-app
    k8s-app: Geolocation-ecr-rep-app
  name: Geolocation-ecr-rep-app
spec:
  selector:
    app: Geolocation-ecr-rep-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8082
  type: LoadBalancer